apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizations-home
  labels:
    app: visualziations-home
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visualizations-home
  template:
    metadata:
      labels:
        app: visualizations-home
    spec:
      containers:
        - name: home
          image: registry.nocovid.group/visualizations-home:latest
          env:
            - name: HOST
              value: nocovid.group
            - name: REGIONS
              valueFrom:
                configMapKeyRef:
                  name: visualizations-current-regions
                  key: yaml
          ports:
            - containerPort: 80
